//
//  Definitions.h
//  MacBitCoin
//
//  Created by Myles Grant on 4/19/13.
//  Copyright (c) 2013 Myles Grant. All rights reserved.
//

#ifndef MacBitCoin_Definitions_h
#define MacBitCoin_Definitions_h

typedef enum{
	BITCOIN_MESSAGE_TYPE_VERSION = 1,
	BITCOIN_MESSAGE_TYPE_VERACK = 2,
	BITCOIN_MESSAGE_TYPE_ADDR = 4,
	BITCOIN_MESSAGE_TYPE_INV = 8,
	BITCOIN_MESSAGE_TYPE_GETDATA = 16,
	BITCOIN_MESSAGE_TYPE_GETBLOCKS = 32,
	BITCOIN_MESSAGE_TYPE_GETHEADERS = 64,
	BITCOIN_MESSAGE_TYPE_TX = 128,
	BITCOIN_MESSAGE_TYPE_BLOCK = 256,
	BITCOIN_MESSAGE_TYPE_HEADERS = 512,
	BITCOIN_MESSAGE_TYPE_GETADDR = 1024,
	BITCOIN_MESSAGE_TYPE_PING = 2048,
	BITCOIN_MESSAGE_TYPE_PONG = 4096,
	BITCOIN_MESSAGE_TYPE_ALERT = 8192,
}BitcoinMessageType;

#define BITCOIN_HEADER_LENGTH 24
#define BITCOIN_COMMAND_LENGTH 12

#define PROTOCOL_VERSION 70001
#define MIN_VERSION_SIZE 87

#define CONNECT_TIMEOUT 1.0
#define READ_TIMEOUT 5.0

#define TAG_FIXED_LENGTH_HEADER 0
#define TAG_RESPONSE_BODY 1

#define MAX_INV_COUNT 50000

typedef enum{
	BITCOIN_INV_OBJ_TYPE_ERROR = 0,
	BITCOIN_INV_OBJ_TYPE_MSG_TX = 1,
	BITCOIN_INV_OBJ_TYPE_MSG_BLOCK = 2,
}BitcoinInvObjectType;

#endif
